name: Deploy to hypersomnia.xyz

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: unnecessary
          
      - name: Adding Known Hosts
        run: ssh-keyscan -H hypersomnia.xyz >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync --exclude={'cache','vendor','builds','/.git','/.github'} -avzP . ubuntu@hypersomnia.xyz:/var/www/html --delete-after --dry-run

      - name: Clear cache
        uses: appleboy/ssh-action@master
        with:
          host: hypersomnia.xyz
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: curl localhost/src/clear_cache.php
