name: Deploy to hypersomnia.xyz

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: unnecessary
          
      - name: Adding Known Hosts
        run: ssh-keyscan -H hypersomnia.xyz >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        # WATCH OUT!!! DO NOT ADD SPACES INSIDE BRACES BETWEEN ARGUMENTS OR THE ENTIRE WEBSITE WILL BE WIPED OUT!
        run: rsync --exclude={'src/config.php','src/data/commits.json','src/data/statistics.json','src/data/visitors.json','src/data/login_attempts.json','src/data/authorized_mappers.json','vendor','builds','.git','.github'} -avzP . ubuntu@hypersomnia.xyz:/var/www/html --delete-after
